version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: my_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb.conf:/etc/mongodb.conf
      - ./mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo_data:
